### ISSUE TITLE
Make Hashtag Code work with MySQL

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/dcs#158]
The RDS instance at AWS is MySQL compatible but the current code is written for PostgreSQL.

**Comment by ethantkoenig** [comment]
I can look into this

**Comment by ethantkoenig** [comment]
Are you referring to https://github.com/unfoldingWord-dev/gogs/blob/develop/models/hashtag.go#L31? I'm not having problems when I run locally (with a MySQL database).
