### ISSUE TITLE
Add Language to Owner API Endpoint

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/dcs#302]
The Organization & User data in the API should begin returning a list of languages that are used in that account.

- [x] languages: [en, fr]

The data is based on the language codes of the repos in that Org or User account. unfoldingWord would probably list these: `en, fr, el-x-koine, hbo`. Data is from the door43_metadata table.

Should appear in at least these:

* https://qa.door43.org/api/swagger#/organization/orgGet
* https://qa.door43.org/api/swagger#/organization/orgListCurrentUserOrgs
* https://qa.door43.org/api/swagger#/organization/orgListUserOrgs
* https://qa.door43.org/api/swagger#/user/userGetCurrent

**Comment by richmahn** [comment]
For orgs/users I call it "repo_languages" to not confuse it with the Gitea returned language setting of the user API.
