### ISSUE TITLE
API Repo Queries

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/dcs#303]
Projects (repos) on DCS need to be queriable based on the following new parameters:

* [x] subject
* [x] book(s)
* [x] language
* [x] checking level (needs refined later)

---

For later...

* [ ] translation style (needs defined)
* [ ] flavor_type
* [ ] flavor (`subject` for RC)
* [ ] checking level (needs refined for SB)

**Comment by richmahn** [comment]
checkingLevel works as a parameter, such as 
https://qa.door43.org/api/catalog/v4?stage=prod&subject=obs%20translation%20notes&checkingLevel=3

Currently it shows any checkingLevel by default. If you give it "1" that will return levels 1 and greater (1, 2 and 3), where 2 would give you (2, 3).
