### ISSUE TITLE
Double Help Links

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/dcs#311]
When you're not logged in, notice the double Help links:
<img width="836" alt="Screen Shot 2020-08-12 at 9 18 41 AM" src="https://user-images.githubusercontent.com/107731/90019780-e2f53e80-dc7c-11ea-9381-83ad2bc209ad.png">

Seen on Version: 1.12.3+235-g5619e7958  .

**Comment by richmahn** [comment]
Yeah, Gitea sneaked that back in from an merge fro upstream. Already removed it.
