### ISSUE TITLE
Doubled Heading Information

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/dcs#312]
Not sure why this information is showing up multiple times but it doesn't look right:
<img width="569" alt="Screen Shot 2020-08-12 at 9 21 56 AM" src="https://user-images.githubusercontent.com/107731/90020100-5eef8680-dc7d-11ea-86cd-13b22a9eeb7d.png">

Seen in Version: 1.12.3+235-g5619e7958

**Comment by richmahn** [comment]
@jag3773 
First heading is from the manifest, showing 
```<title>
<subject>
<language>```

Then it shows whatever was written in the repo's description. While these unfoldingWord repos have a description, I have found many others do not so nice to have the manifest info there at the top to know what one is looking at exactly.

We can remove that, or just show subject and language. Let me know.

**Comment by jag3773** [comment]
@richmahn although the information is valuable, it does not look right in the app, I'd prefer if we remove that altogether.

Perhaps we could put the language information in this bar though?

<img width="1164" alt="Screen Shot 2020-08-14 at 1 41 42 PM" src="https://user-images.githubusercontent.com/107731/90277613-eed73100-de33-11ea-9555-d4e144fc2ecc.png">

**Comment by richmahn** [comment]
@jag3773 Ok, will put it in that bar.

**Comment by jag3773** [comment]
also remove from the regular repo listing page (like an org page)
