### ISSUE TITLE
Description field of Repo not encoded properly

### ISSUE THREAD

**Issue by richmahn** [unfoldingWord/dcs#324]
Something odd going on with the Description field of a repo where on prod, repos like the [Vietnamese Bible](https://git.door43.org/lversaw/vi-vcb15) can't save the Vietnamese to the Description, as the non-Latin characters get changed to question marks:

`Vietnamese Contemporary Bible (Kinh Thánh Hiện Đại)`

gets changed to

`Vietnamese Contemporary Bible (Kinh Thánh Hi?n ??i)`

Yet on QA and Develop DCS I can't even save it, as it gives an error:

`updateRepository: update: Error 1366: Incorrect string value: '\xE1\xBB\x87n \xC4...' for column 'description' at row 1`

On [try.gitea.io](https://try.gitea.io/richtest/Test3) and [gitea.com](https://gitea.com/richmahn/test) it works fine to save that string. So I guess we have something set wrong for the encoding in our DBs?

**Comment by yakob-aleksandrovich** [comment]
This one has been resolved already
